### ISSUE TITLE
Armlook Error

### ISSUE THREAD

**Issue by avedianj** [maridansoft/kodi_armlook#1]
Barev Dzes,
Shnorakalutyun add-oni hamar. Yes henc es addonayi spasum. Hima kani vor hayeren im arachin lezu chi aveli lave enkleren patsatrem inch e problem@ u yete ankleren lav ches asa karogh em tarkmanelu oknutyun kanchem mekin. 

So most shows work perfect the ones I watch most of the time for example Full House (most recent season), Qari Dard, Arm Comedy. But it seems many of the shows on the lesser known networks aren't working at all. I am getting "Error Script failed: Armlook". Just to be sure it wasn't a problem with the video itself and not the addon I went to armlook.com and checked the same episodes and they played fine.

Here is what I know for sure doesn't work:
Armenia TV>Sur Ankyun>22 Feb (this works on the site but not in the addon. Maybe it's because it's the most recent episode (posted today)?
Armenia TV>Harazat Tshnami>06Mar & Episode488-456 (doesn't show anything after episode 456 but the site has all episodes down to episode 1...)
Armenia TV>Tnpesa3>ALL EPISODES
Armenia TV>Full House>ALL EPISODES (this is first season)
Armenia TV>Amnezia>ALL EPISODES (doesn't show episodes 31-01)
Armenia TV>Voice of Armenia 3>Episodes 29Nov-02Oct (may need rutube support)
Armenia TV>Mama> 29Mar & 13 Jun don't work
_did not check past this in Armenia TV catalog_
Kentron>ALL 
Yerkir Media>ALL 
AR-TV>Azdarar>
DAR21>ALL
ShoghakatTV>ALL
PanArmenianTV>ALL (this appears to be pointing to same directory as ShoghakatTV)
H1>ALL
ArmNews>ALL

These don't work in the addon nor the website (so I'm sure it's not something in your hands):
Armenia TV>0199>all episodes
Armenia TV>Yere1>ALL EPISODES
Laym>ALL
Kino24>ALL (don't see this even listed on site)

Then there are a number of "online channels" and "news channels" which show on the site but not on the add-on: see http://www.armlook.com/all-channels 

Sorry, I know it's a lot but thought it might help get it sorted out. Thanks again for all the work on this addon I know myself and my extended family will be using it on Kodi and enjoying not having to go to a browser to watch our favorite shows.

Aprek enker.

Hovik

**Comment by gelinger777** [comment]
Thanks Hovik for the issue. I made it for myself in a very fast way. . I need some time to rework a bit. 
Do you have youtube addon installed?

**Comment by avedianj** [comment]
I do. And again, thanks so much for sharing it. Truly awesome!

**Comment by gelinger777** [comment]
Should be solved. Update from git

**Comment by avedianj** [comment]
Hi, yes when I got your message that it should be solved I re-installed the addon on about 3-4 kodi installations and tested and a lot of what wasn't working before was working then. Yesterday or today however we started noticing things that you had solved not working again with the "Error: Script Failed! Armook" message. 
For example:
Shant>ALL
H1>ALL
Armnews>ALL

There are more but for now I just wanted to let you know whatever you had fixed is broken again. 
That said I know you just made this for yourself and if you don't wish to deal with it I totally respect that. Just want you to know we appreciate the addon and your efforts to create and maintain it.
Thanks,
Hovik

**Comment by gelinger777** [comment]
Some of the youtube were embedded with wrong url. now its fixed too.

**Comment by gelinger777** [comment]
for example H1 http://www.armlook.com/episode/h1-first-channel/with-the-whole-family/episode-27/5423 video does not work on web so it does not work on kodi too. please update and recheck

**Comment by gelinger777** [comment]
http://www.armlook.com/episode/armnews/my-experience/secret-of-lost-church/81  video removed and not work on kodi too. Please if you experience some video that works on web but not on kodi let me know.

**Comment by avedianj** [comment]
Okay I'll check and let you know. Shnorhakalutyun.
Hovik

**Comment by gelinger777** [comment]
not at all .Have a nice day!

**Comment by gelinger777** [comment]
Get the latest version. Now it has LiveTVs  also for most of Armenian channels.
