### ISSUE TITLE
not all shows get displayed

### ISSUE THREAD

**Issue by vortex91** [maridansoft/kodi_armlook#2]
as example when parsing shanttv armlook --> siro gerin--> plugin start from show 155-204 while website has from 1 -204.

**Comment by gelinger777** [comment]
find line 188 in default.py 


def listChannel(url):
  |  
  |  
  | url="http://www.armlook.com/channel/allPrograms/"+url+"/limit/40/offset/0";
  |  
  | req = urllib2.Request(url)
  | req.add_header('User-Agent', 'Mozilla/5.0 (Windows NT 6.1; rv:22.0) Gecko/20100101 Firefox/22.0')
  | response = urllib2.urlopen(req)


and try to play with limit number which is set now to 40 and change it to 250 "/limit/40/offset/0";

**Comment by vortex91** [comment]
already tried that but no luck.  didnt help.  also tried changing line 161 to 250 but that didnt help also.

**Comment by vortex91** [comment]
got me looking further.  Issue is with line 161.  Solved it by removing the limit instead of setting it to 250
 content="http://www.armlook.com/program/allEpisodes/"+url+"/limit";

thanx

**Comment by gelinger777** [comment]
ah yes, you are right. You can push a commit if you like and I will approve it. 
I have no time to make it better. Maybe one time . Closing issue.
